apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-content-converter-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/data/file_content_converter"
